version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: live_score_db
    environment:
      POSTGRES_DB: livescoredb
      POSTGRES_USER: livescoreuser
      POSTGRES_PASSWORD: livescorepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: live_score_app
    depends_on:
      - postgres
    environment:
      DB_URL: postgresql://postgres:5432/livescoredb
      DB_USERNAME: livescoreuser
      DB_PASSWORD: livescorepass
    ports:
      - "8080:8080"
    volumes:
      - match_events:/app/match-events

volumes:
  postgres_data:
  match_events:
